"""empty message

Revision ID: 8405a011bcd8
Revises: 49fb911139d8
Create Date: 2020-05-04 18:06:59.426557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8405a011bcd8'
down_revision = '49fb911139d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
